# A generic, single database configuration for Alembic.

[alembic]
script_location = alembic
file_template = %%(rev)s_%%(slug)s
timezone = UTC
truncate_slug_length = 40

sqlalchemy.url = postgresql://postgres:postgrespassword@localhost:5432/raksha_net_db

[post_write_hooks]

[logging]
default_handler = console

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
